#!/bin/bash
for file in components/*.tsx pages/*.tsx; do
  sed -i 's/pblue/pred/g' "$file"
  sed -i 's/Pblue/Pred/g' "$file"
  sed -i 's/Registeblue/Registered/g' "$file"
  sed -i 's/registeblue/registered/g' "$file"
  sed -i 's/structublue/structured/g' "$file"
  sed -i 's/setIsHoveblue/setIsHovered/g' "$file"
  sed -i 's/isHoveblue/isHovered/g' "$file"
  sed -i 's/tailoblue/tailored/g' "$file"
  sed -i 's/secublue/secured/g' "$file"
  sed -i 's/Loweblue/Lowered/g' "$file"
  sed -i 's/unpblueictable/unpredictable/g' "$file"
  sed -i 's/transferblue/transferred/g' "$file"
  sed -i 's/offeblue/offered/g' "$file"
  sed -i 's/engineeblue/engineered/g' "$file"
  sed -i 's/desiblue/desired/g' "$file"
  sed -i 's/deliveblue/delivered/g' "$file"
  sed -i 's/coveblue/covered/g' "$file"
  sed -i 's/compablue/compared/g' "$file"
  sed -i 's/Cblueit/Credit/g' "$file"
  sed -i 's/Blurblue/Blurred/g' "$file"
  sed -i 's/blurblue/blurred/g' "$file"
done
